run:
  timeout: 5m
  skip-dirs-use-default: true
  skip-files:
    - ".*_test\.go$" # Optionally skip test files from some linters if needed

linters-settings:
  errcheck:
    # Report about not checking errors in type assertions: `a := b.(MyType)`
    check-type-assertions: true
    # Report about not checking errors in assignments: `a = b`
    check-blank: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15 # Adjust as needed
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive # Replaces golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen # Test functions can be long
        - gocyclo
    # Example: Disabling a specific linter for a specific path
    # - path: cmd/imageconverter/main.go
    #   linters:
    #     - noctx

# Options for fixing issues automatically (use with caution in CI)
# fix: false
